[ENH] Faster VideoStimulus Encode function
pulse2percept/pulse2percept pull request #458
Opened 2022-02-01 07:17 UTC by narenberg

## Description

Attempt to speed up VideoStimulus encode function by cythonizing and optimizing loops. All tests pass, speedup is minimal. It is worth wondering whether the change is worth merging into master.

Closes #377 

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation change

## Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

For detailed information on these and other aspects, see the contribution guidelines: https://pulse2percept.readthedocs.io/en/latest/developers/contributing.html

2022-02-08 14:50 UTC, mbeyeler reviewed
Let's discuss this at our next meeting. The problem currently is that there are still a lot of necessary Python calls in the loop (e.g., `Stimulus`, `BiphasicPulse`), so you can't release the gil. This would explain why the speedup is limited... 

Making this work is tricky. You'd have to strip all the Python overhead and e.g. purely operate on arrays. However, currently the array changes shape on each iteration, which is also slow.

One way might be to:

1.  Do all the Python/error checks outside the Cython function
2.  Use p2p to create `BiphasicPulse` outside Cython. Then only pass the time & data arrays of the `BiphasicPulse` object
3.  Preallocate the time & data arrays of the final `Stimulus` that will be created
4.  Fill the values of the arrays in the loop without calling out to Python objects

2022-02-08 14:50 UTC, mbeyeler commented on pulse2percept/stimuli/_videos.pyx
> +            s = Stimulus(amp * enc_data, time=pulse.time, electrodes=e)
The problem with this is that you have Python overhead in the loop (from calling `Stimulus`), so I wouldn't expect this to be much faster than pure Python...

2022-02-22 23:48 UTC, narenberg commented
I'm still not sure how necessary this PR is since the majority of the VideoStatus encoding test time came from creating the BostonTrain Stimulus.

2022-03-08 07:26 UTC, jgranley requested changes
Looks good, except maybe change the error given to the user to be a typeerror instead of a key error. this is more useful to the user, otherwise they might be confused why they get a key error when they never even worked with any dictionaries

2022-03-08 07:26 UTC, jgranley commented on pulse2percept/models/granley2021.py
> +                raise KeyError(f"All stimuli must be BiphasicPulseTrains with no " +
I think this should be a type error: The problem is that the passed stimuli was not the correct type

2022-03-17 06:28 UTC, jgranley reviewed
The code all looks good to me. I am curious what the speedup is now. Like Nick mentioned, is it worth adding more cython / complication if it doesn't speed up?

Either way, I think removing the lines that check stimulus metadata (stimuli/base.py 248-252) is good. I only added this so that metadata was always collected and had a unified structure across stimuli. In this situation, the metadata is not even used anywhere, so theres no point in collecting it if its slow

2022-03-23 02:59 UTC, mbeyeler commented
The reason it's not much faster is that almost every Cython line has Python overhead. But there should be a faster way - let me see what I can do

2022-03-23 04:33 UTC, mbeyeler commented
If you use an outer product instead of all the concatenate, stim append, and dictionary business, you can go down from:

```
vid = p2p.stimuli.BostonTrain(as_gray=True, resize=(20, 20))
%timeit -n3 -r3 vid.encode()
6.54 s ± 166 ms per loop (mean ± std. dev. of 3 runs, 3 loops each)
```

to

```
vid = p2p.stimuli.BostonTrain(as_gray=True, resize=(20, 20))
%timeit -n3 -r3 vid.encode()
1.99 ms ± 405 µs per loop (mean ± std. dev. of 3 runs, 3 loops each)
```

No Cython required!
Now even the full-size RGB `BostonTrain` encodes in 1.35s, and that's on my laptop.

2022-03-23 05:05 UTC, merged