[FIX] Add check for empty stimulus
pulse2percept/pulse2percept pull request #522
Opened 2023-02-01 10:26 UTC by tallyhawley

## Description

Adds a check in `ProsthesisSystem`'s `stim` setter. This causes empty inputs (e.g. `stim=[]` or `stim={}`) to set `ProsthesisSystem.stim` to `None`. Previously, the setter would try to create a `Stimulus` object which would cause various errors depending on the type (dict, list, etc.). With this change, passing an empty stimulus will now have the same effect as passing `stim=None`, which is that calling `model.predict_percept` on an implant with this stimulus will simply output `None` without throwing an error.

Closes #498 

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2023-02-01 20:06 UTC, jgranley commented
Quick and simple fix, looks great! One minor change with np.ndarray and then it should be good to merge

2023-02-01 20:07 UTC, jgranley requested changes

2023-02-01 23:40 UTC, tallyhawley commented on pulse2percept/implants/base.py
> +        elif isinstance(data, (list, tuple, dict)) and not data:
`np.ndarray` can't be implicitly converted to boolean, so I've added a separate check for `np.ndarray`, defining an empty ndarray as one of size 0.

2023-02-02 02:14 UTC, jgranley approved these changes

2023-02-02 02:17 UTC, merged