[ENH] Implemented TorchAxonMapSpatial
pulse2percept/pulse2percept pull request #618
Opened 2024-05-07 03:05 UTC by whuang602

## Description

Implemented TorchAxonMapSpatial class with constructor and forward function. Forward function may need additional post processing steps. 

AxonMapSpatial now allows for self.engine to be torch, on top of jax, cython, and serial. 

Note that this code does use switch statements in the self.engine validation portion, so Python 3.10 is required. But I can definitely switch it back to normal if-else if necessary.

Closes #614 

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation change

## Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

For detailed information on these and other aspects, see the contribution guidelines: https://pulse2percept.readthedocs.io/en/latest/developers/contributing.html

2024-06-10 01:22 UTC, tallyhawley commented on pulse2percept/models/beyeler2019.py
> +            raise ValueError("Engine Selection Conflict : Constructing TorchAxonMapSpatial with engine", p2pmodel.engine)
you should be able to construct a torchmodel from any axonmapspatial object, we can't guarantee that the torchmodel is being used internally within the p2pmodel
i.e. in the onnx conversion, we will most likely be passing in a p2pmodel with the default cython engine

2024-06-10 20:19 UTC, jgranley requested changes

2024-06-10 20:19 UTC, jgranley commented on pulse2percept/models/beyeler2019.py
> +            raise NotImplementedError("Unknown engine selected")
Very minor but please have the error state what the unknown engine provided is and what the options are.

2024-06-10 20:19 UTC, jgranley commented on pulse2percept/models/beyeler2019.py
> +            self.is_built = True
Do we still need this self.is_built here?

2024-06-10 20:19 UTC, jgranley commented on pulse2percept/models/beyeler2019.py
> +                                                        np.array([earray[e].y for e in stim.electrodes], dtype=np.float32))]).to(self.device)
Also minor, but prefer to use torch.tensor(..., device=device) instead of torch.tensor(...).to(device) to avoid unnecessary copy

2024-06-10 20:19 UTC, jgranley commented on pulse2percept/models/beyeler2019.py
> +        intensities = torch.max(intensities, dim=-1).values
I think we need one more line to match previous behavior, basically clip anything beneath self.thresh_percept to be 0

2024-06-10 20:22 UTC, jgranley commented on pulse2percept/models/beyeler2019.py
> +        elif self.engine == 'torch':
you can also go ahead and put self.axon_contrib on the correct device here

2024-06-10 20:24 UTC, jgranley commented on pulse2percept/models/beyeler2019.py
> +        elif self.engine == 'torch':
wait just kidding doing it in the TorchAxonMapSpatial is better

2024-06-10 20:27 UTC, jgranley commented on pulse2percept/models/beyeler2019.py
> +        amp = torch.tensor(stim[:, ::1], dtype=torch.get_default_dtype()) # I_score
you can just slice it here and assume its already in a tensor format

2024-06-10 20:46 UTC, jgranley commented on pulse2percept/models/beyeler2019.py
> +            e_locs = torch.tensor([(x,y) for x,y in zip(np.array([earray[e].x for e in stim.electrodes], dtype=np.float32),
torch.stack().to() will be considerably faster than this for large number of electrodes

2024-06-10 22:43 UTC, jgranley commented on pulse2percept/models/beyeler2019.py
> +        intensities = torch.max(intensities, dim=-1).values
intensities = torch.where(intensities > self.thresh_percept, intensities, 0)

2024-06-11 00:29 UTC, jgranley approved these changes

2024-06-13 06:17 UTC, merged